import jsPDF from "jspdf";

// Export one chat answer as an official-style PDF: the full answer first,
// then a numbered "References & Sources" section at the end mapping every
// [#N] citation to its source document + verbatim quote — the way a legal
// brief lists its authorities/exhibits.
export function exportAnswerPdf({ question, answer, sources }) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const M = 48;
  const W = doc.internal.pageSize.getWidth() - M * 2;
  const PH = doc.internal.pageSize.getHeight();
  let y = M;

  const ensure = (h) => { if (y + h > PH - M) { doc.addPage(); y = M; } };
  const write = (text, { size = 10.5, bold = false, gap = 4, color = [28, 30, 42], indent = 0, font = "times" } = {}) => {
    doc.setFont(font, bold ? "bold" : "normal");
    doc.setFontSize(size);
    doc.setTextColor(color[0], color[1], color[2]);
    doc.splitTextToSize(String(text ?? ""), W - indent).forEach((l) => {
      ensure(size + gap); doc.text(l, M + indent, y); y += size + gap;
    });
  };
  const rule = () => { doc.setDrawColor(220, 215, 205); doc.line(M, y, M + W, y); y += 10; };

  // ── Header ──
  write("LEGAL ADVISOR — ANSWER EXPORT", { size: 15, bold: true, color: [35, 74, 82] });
  if (question) write("Question: " + question, { size: 11, bold: true, gap: 5 });
  write("Generated " + new Date().toLocaleString(), { size: 8.5, color: [120, 120, 130], gap: 8 });
  rule();

  // ── Answer body (render Markdown structure into the PDF) ──
  (answer || "").split("\n").forEach((raw) => {
    const line = raw.replace(/\*\*/g, "").replace(/`/g, "").replace(/^\s*[-*]\s+/, "• ");
    if (!line.trim()) { y += 5; return; }
    if (/^#{1,3}\s/.test(raw)) {
      y += 6;
      write(raw.replace(/^#{1,3}\s/, "").replace(/\*\*/g, ""), { size: 12.5, bold: true, color: [35, 74, 82], gap: 5 });
    } else if (line.startsWith("•")) {
      write(line, { indent: 14 });
    } else if (/^\s*\d+\.\s/.test(line)) {
      write(line.trim(), { indent: 14 });
    } else {
      write(line);
    }
  });

  // ── References & Sources (the numbered authorities at the end) ──
  const all = sources || [];
  const cited = all.filter((s) => (s.verified_facts || []).length > 0);
  const refs = (cited.length ? cited : all).slice().sort((a, b) => (a.index || 0) - (b.index || 0));
  if (refs.length) {
    y += 12; ensure(26);
    write("REFERENCES & SOURCES", { size: 13, bold: true, color: [35, 74, 82] });
    rule();
    refs.forEach((s) => {
      const meta = [s.date, s.from_email, s.page].filter(Boolean).join("  ·  ");
      write(`[#${s.index}]  ${s.title || s.type || "source"}`, { bold: true, size: 10, gap: 3 });
      if (meta) write(meta, { size: 8.5, color: [110, 110, 120], indent: 16, gap: 3 });
      (s.verified_facts || []).slice(0, 4).forEach((f) => {
        if (f.verbatim_quote) write(`“${f.verbatim_quote}”`, { size: 9, color: [80, 80, 95], indent: 16, gap: 3, font: "times" });
      });
      y += 4;
    });
  }

  y += 10; ensure(20);
  write("Every factual claim above is grounded in the cited source. Generated by the Mango Tree Evidence Engine.",
    { size: 8, color: [140, 140, 150] });

  const stamp = new Date().toISOString().slice(0, 10);
  doc.save(`legal_answer_${stamp}.pdf`);
}
